name: 'OpenID Connect login for NuGet'
description: 'Enable using a GitHub Actions OpenID Connect (OIDC) token in the NuGet credential provider.'
author: 'Joel Verhagen'

branding:
  icon: package
  color: blue

inputs:
  username:
    description: 'The user account that has the configured federated token settings configured.'
    required: true
  package-source:
    description: 'The package source URL to allow token authentication with.'
    required: true
    default: 'https://api.nuget.org/v3/index.json'
  audience:
    description: 'The desired audience claim to use for the OIDC token. Defaults to nuget.org.'
    required: true
    default: 'nuget.org'

outputs:
  token-info:
    description: 'The GitHub Actions OIDC token info used by the NuGet credential provider'

runs:
  using: node20
  main: dist/index.js
